server:
  port: 8090
spring:
  application:
    name: microservice-provider-user

  rabbitmq:
    host: 10.166.104.129
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        myRabbit: # 表示定义的名称，用于于binding整合,对应bindings的binder配置项
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: ${spring.rabbitmq.host}
                port: ${spring.rabbitmq.port}
                username: ${spring.rabbitmq.username}
                password: ${spring.rabbitmq.password}
                virtual-host: ${spring.rabbitmq.virtual-host}
      bindings:
        hello_output: # channelName
          destination: hello_exchange # 表示要使用的Exchange名称定义
          content-type: text/plain # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          binder: myRabbit # 设置要绑定的消息服务的具体设置
      rabbit:
        bindings:
          hello_output:
            producer:
              ttl: 3000
              routingKeyExpression: '''hello'''
              autoBindDlq: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/,http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


