server:
  port: 8092
spring:
  application:
    name: microservice-provider-user

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8760/eureka/,http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

  rabbitmq:
#    host: 192.168.43.70
    port: 5672
    username: admin
    password: 123456

