server:
  port: 8761

spring:
  application:
    name: micoservice-eureka-server

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8760/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 0
    enable-self-preservation: true