server:
  port: 8082
spring:
  application:
    name: microservice-consumer-movie

security:
  enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
  instance:
    prefer-ip-address: true

ribbon:
  ConnectTimeout: 3000 #请求连接超时时间
  ReadTimeout: 5000 #请求处理的超时时间
  MaxAutoRetries: 1 #对当前实例的重试次数
  MaxAutoRetriesNextServer: 2 #切换实例的重试次数
  OkToRetryOnAllOperations: true #是否对所有操作请求都进行重试
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule #配置负载均衡策略


