server:
  port: 8084

spring:
  rabbitmq:
    host: 10.166.104.226
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    publisher-returns: true
    publisher-confirms: true
    template:
      mandatory: true
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        acknowledge-mode: manual
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        myRabbit: # 表示定义的名称，用于于binding整合,对应bindings的binder配置项
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: ${spring.rabbitmq.host}
                port: ${spring.rabbitmq.port}
                username: ${spring.rabbitmq.username}
                password: ${spring.rabbitmq.password}
                virtual-host: ${spring.rabbitmq.virtual-host}
      bindings:
        hello_output: # channelName
          destination: hello_output_ex # 表示要使用的Exchange名称定义
          content-type: text/plain # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          binder: myRabbit # 设置要绑定的消息服务的具体设置
          group: hello
        hello_input:
          destination: hello_output_ex
          content-type: text/plain
          binder: myRabbit
          group: hello
#      rabbit:
#        bindings:
#          hello_input: # channelName
#            consumer:
#              bindingRoutingKey: hello
#          hello_output:
#            producer:
#              routingKeyExpression: '''hello'''

management.endpoints.web.exposure.include: bindings #通过Actuator组件实现对binding的控制

tutorial:
  client:
    duration: 10000
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/