server:
  port: 8090

spring:
  rabbitmq:
    host: 10.164.16.155
    port: 5672
    username: admin
    password: 123456
    virtual-host: testVH

  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        myRabbit: # 表示定义的名称，用于于binding整合,对应bindings的binder配置项
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 10.166.104.167
                port: 5672
                username: admin
                password: 123456
                virtual-host: testVH

      bindings: # 服务的整合处理
        hello_output: # 这个名字是一个通道的名称，在分析具体源代码的时候会进行说明
          destination: hello_topic_ex # 表示要使用的Exchange名称定义
          content-type: text/plain # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          binder: myRabbit # 设置要绑定的消息服务的具体设置
          group: hello_que_1
#          producer:
#            routingKeyExpression: '''hello.Jim'''

  profiles:
    active: usage_message

logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 10000
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/