server:
  port: 8000
spring:
  application:
    name: microservice-springboot-admin
security:
  enabled: false
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
#  instance:
#    prefer-ip-address: true



